version: '3.8'

services:
  marketflow:
    build:
      context: .. 
      dockerfile: deployments/Dockerfile
    container_name: marketfuck
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    networks:
      - marketfuck-net

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketfuck
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - marketfuck-net
    ports:
      - "5432:5432"




  redis:
    image: redis:6-alpine
    container_name: redis
    networks:
      - marketfuck-net

networks:
  marketfuck-net:
    driver: bridge

volumes:
  postgres-data:
