CREATE TABLE IF NOT EXISTS aggregated_prices (
	id SERIAL PRIMARY KEY,
	pair_name TEXT NOT NULL,
	exchange TEXT NOT NULL,
	timestamp TIMESTAMP NOT NULL,
	average_price DOUBLE PRECISION NOT NULL,
	min_price DOUBLE PRECISION NOT NULL,
	max_price DOUBLE PRECISION NOT NULL
);